source 'http://rubygems.org'

gem 'rails', '3.0.5'

gem "mongoid", "~> 2.0.2"
gem "bson_ext", "~> 1.3.1"

gem 'haml'
gem 'will_paginate'
gem "compass", ">= 0.10.6"

gem 'rest-client'
gem 'json'

gem "jquery-rails"
